### ISSUE TITLE
Books: add icon next to the title or put them in a separate sub section

### ISSUE THREAD

**Issue by fadehelix** [acism/awesome-scrum-master#11]
What? 
My idea here is to "warn" the **reader** that particular item on the list is a book and not just link to any online resource.
Why? 
Because in order to read the book you have to buy it and it's usually much more to read than in any resource on the internet like an article, youtube movie, presentation etc. 

What do you think?

**Comment by kat-kap** [comment]
Side question - does this mean that we only want to have books in here? I am asking because I was thinking about adding some internet resources here, links to interesting articles, etc. So juts to clarify -is this ok?

**Comment by fadehelix** [comment]
IMO "book" is only one of many types, but it's different :) Personally I would like to have here as many "online" resources as possible and books as a "special" resource - that's why I would like to mark them. Books are great extension to the topic for people who want's do spend their time and money to dig deeper.
I am not sure if it's clear for you :P

**Comment by kat-kap** [comment]
Clear! And I think it's a good idea :) +1

**Comment by kat-kap** [comment]
By "icons" you mean a book cover picture? Or just a generic symbol like this: 📖?

**Comment by fadehelix** [comment]
Generic symbol like 📖 is enough for me 🤟

**Comment by fadehelix** [comment]
Thanks @kat-kap for completing this task :)
